import {
  Login,
  Group,
  GroupDetail,
  GroupInsight,
  GroupHistory,
  Kid,
  RegisterKid,
  KidsDetail,
  RoutePlan,
  Store,
  Team,
  RegisterTeam,
  Data,
  Profile,
  SpecialProgram,
  SpecialProgramDetail,
  KidHistory,
  History,
  Page404,
} from "../pages";
import { FormattedMessage } from "react-intl";

import DashIcon from "../assets/icons/HeaderIcons/Category.png";
import RouteIcon from "../assets/icons/HeaderIcons/icon.png";
import StoreIcon from "../assets/icons/HeaderIcons/u_store.png";
import KidIcon from "../assets/icons/HeaderIcons/2 User.png";
import TeamIcon from "../assets/icons/HeaderIcons/3 User.png";
import StarOut from "../assets/icons/starOutlinned.png";
import HistoryIcon from "../assets/icons/HeaderIcons/historyIcon.png";
import GroupIcon from "../assets/icons/HeaderIcons/chatIcon.png";
import DataIcon from "../assets/icons/HeaderIcons/Document.png";

import { ROLES } from "../utils/constants";

const Component = () => <div> Comming Soon! </div>;

export const Routes = [
  {
    exact: true,
    path: "/",
    component: Login,
    private: false,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/dashboard",
    component: Component,
    private: true,
    title: <FormattedMessage id="dashboard" />,
    icon: <img src={DashIcon} />,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/history",
    component: History,
    private: true,
    title: <FormattedMessage id="history" />,
    icon: <img src={HistoryIcon} />,
    roles: [],
    permissions: [],
  },
  // {
  //     exact: true,
  //     path: '/specialProgram',
  //     component: SpecialProgram,
  //     private: true,
  //     title: <FormattedMessage id="special_program" />,
  //     icon: <img src={StarOut} style={{ height: 20, width: 20 }} />,
  //     roles: [],
  //     permissions: [],
  // },
  //   {
  //     exact: true,
  //     path: "/specialProgram/:id",
  //     component: SpecialProgramDetail,
  //     private: true,
  //     roles: [],
  //     permissions: [],
  //   },
  {
    exact: true,
    path: "/routePlan",
    component: RoutePlan,
    private: true,
    title: <FormattedMessage id="route_plan" />,
    icon: <img src={RouteIcon} />,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/store",
    component: Store,
    private: true,
    title: <FormattedMessage id="store" />,
    icon: <img src={StoreIcon} />,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/kids",
    component: Kid,
    private: true,
    title: <FormattedMessage id="kids" />,
    icon: <img src={KidIcon} />,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/kids/register",
    component: RegisterKid,
    private: true,
    roles: [],
    permissions: [],
  },

  {
    exact: true,
    path: "/kids/:id/history",
    component: KidHistory,
    private: true,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/kids/:id",
    component: KidsDetail,
    private: true,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/teams",
    component: Team,
    private: true,
    title: <FormattedMessage id="staff" />,
    icon: <img src={TeamIcon} />,
    roles: [ROLES.mngr, ROLES.crdntr],
    permissions: [],
  },
  {
    exact: true,
    path: "/teams/register",
    component: RegisterTeam,
    private: true,
    roles: [ROLES.mngr, ROLES.crdntr],
    permissions: [],
  },
  {
    exact: true,
    path: "/groups",
    component: Group,
    private: true,
    title: <FormattedMessage id="groups" />,
    icon: <img src={GroupIcon} />,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/groups/:id",
    component: GroupDetail,
    private: true,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/groups/:id/history",
    component: GroupHistory,
    private: true,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/groups/:id/insights",
    component: GroupInsight,
    private: true,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "/data",
    component: Data,
    private: true,
    title: <FormattedMessage id="data" />,
    icon: <img src={DataIcon} />,
    roles: [ROLES.mngr],
    permissions: [],
  },
  {
    exact: true,
    path: "/profile",
    component: Profile,
    private: true,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "*",
    component: Page404,
    private: false,
    roles: [],
    permissions: [],
  },
  {
    exact: true,
    path: "*",
    component: Page404,
    private: true,
    roles: [],
    permissions: [],
  },
];
